Cleanup check_java_env() function

diff --git a/java-utils/java-functions b/java-utils/java-functions
--- a/java-utils/java-functions
+++ b/java-utils/java-functions
@@ -137,7 +137,6 @@ set_jvm()
 }
 
 # Set the classpath
-# This requires a valid JAVA_HOME, JAVACMD, and JAVA_LIBDIR
 set_classpath()
 {
     local IFS
@@ -214,7 +213,6 @@ run()
 }
 
 # Set JVM-related directories
-# Requires a correct $JAVA_LIBDIR, $JAVA_HOME and $JAVA_CMD
 set_jvm_dirs()
 {
     local re
@@ -339,7 +337,6 @@ link_jar_repository() {
 
 
 # Finds a specific extention (jar or directory)
-# Requires a correct $JAVA_LIBDIR, $JAVAVER_LIBDIR and $JVM_LIBDIR
 find_jar()
 {
     local IFS=:
@@ -382,20 +379,20 @@ find_jar()
 
 
 ## Checks java environment
-check_java_env() {
+check_java_env()
+{
+    # This is usually set by set_jvm
+    if [ -z "${JAVA_HOME}" ] ; then
+	echo "$0: error: JAVA_HOME must be set" >&2
+	return 1
+    fi
 
-   # This is usually set by set_jvm
-   if [ -z "$JAVA_HOME" ] ; then
-      echo "$0: error: JAVA_HOME must be set" >&2
-      return 1
-   fi
+    if [ -z "${JAVACMD}" ] ; then
+	echo "$0: error: JAVACMD must be set" >&2
+	return 2
+    fi
 
-   if [ -z "$JAVACMD" ] ; then
-      echo "$0: error: JAVACMD must be set" >&2
-      return 2
-   fi
-
-   return 0
+    return 0
 }
 
 
